# Home Assistant Add-on Configuration for LMeals
name: "LMeals"
version: "0.1.0"
slug: "lmeals"
description: "A self-hosted recipe manager with a powerful AI scraper."
url: "https://github.com/vgyy4/LMeals"
startup: "application"
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
boot: "auto"
webui: "http://[HOST]:[PORT:8000]"
ports:
  8000/tcp: 8000
options:
  GROQ_API_KEY: ""
  GROQ_MODEL: "llama3-70b-8192"
schema:
  GROQ_API_KEY: "password"
  GROQ_MODEL: "str"
environment:
  GROQ_API_KEY: "{options.GROQ_API_KEY}"
  GROQ_MODEL: "{options.GROQ_MODEL}"

