# Home Assistant Add-on Configuration for LMeals
name: "LMeals"
version: "0.1.0"
slug: "lmeals"
description: "A self-hosted recipe manager with a powerful AI scraper."
url: "https://github.com/vgyy4/LMeals"
startup: "application"
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
boot: "auto"
webui: "http://[HOST]:[PORT:8000]"
ingress: true
ingress_port: 8000
ingress_entry: /


